export default {

  ADD_TASK_TO_DONE: 'ADD_TASK_TO_DONE',
  ADD_TASK_TO_TODO: 'ADD_TASK_TO_TODO',

  REMOVE_TASK_FROM_DONE: 'REMOVE_TASK_FROM_DONE',
  REMOVE_TASK_FROM_TODO: 'REMOVE_TASK_FROM_TODO',

  EDIT_TASK: 'EDIT',

  SET_SEARCH_TERMS: 'SET_SEARCH_TERMS',

};
